services:
  postgres:
    image: postgres:17.7
    container_name: smart-polls-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - smart-polls-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: ollama-mitmproxy
    stdin_open: true
    tty: true
    command: mitmweb --web-host 0.0.0.0 --web-port 8081 --mode reverse:http://host.docker.internal:11434 --listen-port 8080
    ports:
      - "11435:8080"
      - "11436:8081"
    volumes:
      - ollama-mitmproxy:/home/mitmproxy/.mitmproxy


volumes:
  smart-polls-postgres-data:
  ollama-mitmproxy:
