server:
  port: ${SMART_POLLS_PORT:8080}

spring:
  application:
    name: smart-polls

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  ai:
    openai:
      base-url: ${OPENAI_URL}
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

