spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  ai:
    openai:
      chat:
        base-url: ${OPENAI_CHAT_URL:http://localhost:11435}
        options:
          model: ${OPENAI_CHAT_MODEL:gemma3:4b}
      embedding:
        base-url: ${OPENAI_EMBEDDING_URL:http://localhost:11435}
        options:
          model: ${OPENAI_EMBEDDING_MODEL:embeddinggemma:300m}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
